# Generated by Django 6.0 on 2025-12-27 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_reliability_index', models.CharField(max_length=50, verbose_name='Index daňovej spoľahlivosti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy overené')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_status', to='companies.company')),
            ],
            options={
                'verbose_name': 'DPH Status',
                'verbose_name_plural': 'DPH Statusy',
                'db_table': 'analysis_vatstatus',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50, verbose_name='Zdroj dlhu')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Suma v EUR')),
                ('date_of_record', models.DateField(verbose_name='Dátum evidencie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené v DB')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='companies.company')),
            ],
            options={
                'verbose_name': ('Dlh',),
                'verbose_name_plural': ('Dlhy',),
                'db_table': 'analysis_debt',
                'indexes': [models.Index(fields=['company', 'date_of_record'], name='analysis_de_company_faaf3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='Skóre')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Dátum výpočtu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='companies.company')),
            ],
            options={
                'verbose_name': 'Rizikové skóre',
                'verbose_name_plural': 'História rizikového skóre',
                'db_table': 'analysis_riskscore',
                'ordering': ['-calculation_date'],
                'indexes': [models.Index(fields=['company', 'calculation_date'], name='analysis_ri_company_579d11_idx')],
            },
        ),
    ]
