# Generated by Django 6.0 on 2025-12-27 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='Ulica a číslo')),
                ('city', models.CharField(max_length=255, verbose_name='Mesto')),
                ('zip_code', models.CharField(max_length=10, verbose_name='PSČ')),
                ('country', models.CharField(max_length=50, verbose_name='Krajina')),
            ],
            options={
                'verbose_name': 'Adresa',
                'verbose_name_plural': 'Adresy',
                'db_table': 'companies_address',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ico', models.CharField(max_length=8, unique=True, verbose_name='IČO')),
                ('name', models.CharField(max_length=255, verbose_name='Obchodný názov')),
                ('legal_form', models.CharField(max_length=100, verbose_name='Právna forma')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('registration_date', models.DateField(verbose_name='Dátum vzniku')),
                ('last_updated_from_source', models.DateTimeField(blank=True, null=True, verbose_name='Naposledy synchronizované')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.address', verbose_name='Sídlo')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmy',
                'db_table': 'companies_company',
            },
        ),
    ]
